2018-01-19 18:48:00,064 ERROR: Exception on / [GET] [in c:\program files (x86)\python36-32\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files (x86)\python36-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\calc\package\routes.py", line 35, in index
    next_url=next_url, prev_url=prev_url)
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\calc\package\templates\_post.html", line 15, in template
    {% endset %}
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\calc\package\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\calc\package\templates\base.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "c:\program files (x86)\python36-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\program files (x86)\python36-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\program files (x86)\python36-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\program files (x86)\python36-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\calc\package\templates\base.html", line 53, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\calc\package\templates\index.html", line 12, in block "app_content"
    {% include '_post.html' %}
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\calc\package\templates\_post.html", line 15, in template
    {% endset %}
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\parser.py", line 185, in parse_set
    drop_needle=True)
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\parser.py", line 223, in parse_if
    drop_needle=True)
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "c:\program files (x86)\python36-32\lib\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endset'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'endif'. The innermost block that needs to be closed is 'if'.
2018-01-19 18:50:55,710 INFO: Mavki startup [in C:\calc\package\__init__.py:51]
2018-01-19 21:39:07,529 INFO: Mavki startup [in C:\calc\package\__init__.py:51]
2018-01-19 21:45:03,688 ERROR: Exception on /unfollow/n_xhg [GET] [in c:\program files (x86)\python36-32\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files (x86)\python36-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\calc\package\routes.py", line 165, in unfollow
    flash(_('You are no longer following %(user1)!', uesr1=username))
  File "c:\program files (x86)\python36-32\lib\site-packages\flask_babel\__init__.py", line 556, in gettext
    return s if not variables else s % variables
KeyError: 'user1'
2018-01-19 21:50:22,694 INFO: Mavki startup [in C:\calc\package\__init__.py:51]
2018-01-19 21:52:07,065 INFO: Mavki startup [in C:\calc\package\__init__.py:51]
2018-01-19 21:52:12,686 ERROR: Exception on /unfollow/n_xhg [GET] [in c:\program files (x86)\python36-32\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\program files (x86)\python36-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\calc\package\routes.py", line 165, in unfollow
    flash(_('You are no longer following %(user1)s!', uesr1=username))
  File "c:\program files (x86)\python36-32\lib\site-packages\flask_babel\__init__.py", line 556, in gettext
    return s if not variables else s % variables
KeyError: 'user1'
2018-01-19 22:23:55,428 INFO: Mavki startup [in C:\calc\package\__init__.py:51]
